Redis:
  Password: "yHy0d2zdBlRmaSPj3CiBwEv5V3XxBTLTrCsGW7ntBnzhfxPxXJS6Q1aTtR6DSfAtCZr2VxWnsungXHTcF94a4bsWEpGAvjL6XMU"
  Host: "127.0.0.1"
  MaxConnections: 20
  Threads: 10
  Port: 6379
  TimeOut: 90000
  useSSL: false
  #useful if SSL is disabled
  #also currently EncryptMessages is broken, meaning it must always be true or else it won't work
  EncryptMessages: true
  EncryptionKey: "16CHARACTERS KEY"
  MacKey: "16CHARACTERS KEY"

Channels:
  - "Channel1"
  - "Channel2"
  - "Channel3"