main: net.limework.core.LimeworkSpigotCore
name: LimeworkSpigotCore
version: ${project.version}
author: limework.net
api-version: 1.13
softdepend:
  - Skript
commands:
  control:
    description: "server control"
    permission: "admin.use"
  reloadredis:
    description: "server control"
    permission: "admin.use"