main: net.limework.core.Redisk
name: Redisk
version: ${project.version}
authors: [Govindas, ham1255, DaemonicKing]
api-version: 1.13
softdepend:
  - Skript
commands:
  reloadredis:
    description: "Restart redis connection"
    permission: "admin.use"