main: net.limework.core.LimeworkSpigotCore
name: LimeworkSpigotCore
version: ${project.version}
author: limework.net
api-version: 1.13
softdepend:
  - Skript
commands:
  reloadredis:
    description: "Restart redis connection"
    permission: "admin.use"